"""Database creation

Revision ID: 17234586c1ad
Revises: 270137f0e3a8
Create Date: 2023-09-11 18:20:18.954274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17234586c1ad'
down_revision: Union[str, None] = '270137f0e3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
