"""Database creation

Revision ID: 22bc178694ad
Revises: 
Create Date: 2023-09-04 21:44:30.188708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22bc178694ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('telephone', sa.Integer(), nullable=False),
            sa.Column('username', sa.String(), nullable=False),
            sa.Column('password', sa.String(), nullable=False),
            sa.Column('register_at', sa.TIMESTAMP(), nullable=True),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('chat_name', sa.String(), nullable=False),
            sa.Column('username', sa.String(), nullable=False),
            sa.Column('user_created_id', sa.Integer(), nullable=True),
            sa.Column('register_at', sa.TIMESTAMP(), nullable=True),
            sa.ForeignKeyConstraint(['user_created_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('text', sa.String(), nullable=True),
            sa.Column('user_created_id', sa.Integer(), nullable=True),
            sa.Column('time_send', sa.TIMESTAMP(), nullable=True),
            sa.Column('is_read', sa.Boolean(), nullable=True),
            sa.ForeignKeyConstraint(['user_created_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('chats')
    op.drop_table('users')
    # ### end Alembic commands ###
