"""Database creation

Revision ID: 51521452c1eb
Revises: 36fba557eb18
Create Date: 2023-09-11 14:41:30.355099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51521452c1eb'
down_revision: Union[str, None] = '36fba557eb18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_chat_relations')
    op.drop_table('message')
    op.drop_table('chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('chat_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('chat_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('register_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_created_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_created_id'], ['user.id'], name='chat_user_created_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_created_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_send', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_created_id'], ['user.id'], name='message_user_created_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_pkey')
    )
    op.create_table('user_chat_relations',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name='user_chat_relations_chat_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_chat_relations_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'chat_id', name='user_chat_relations_pkey')
    )
    # ### end Alembic commands ###
