"""Database creation

Revision ID: 578f3d3a4c4c
Revises: 5e3b31d1b46f
Create Date: 2023-09-12 14:13:07.320605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578f3d3a4c4c'
down_revision: Union[str, None] = '5e3b31d1b46f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
